### ISSUE TITLE
Pzem reads 2-way?

### ISSUE THREAD

**Issue by Tpro4391** [mandulaj/PZEM-004T-v30#36] opened 2020-10-02 02:03 UTC
Other electronic meters often distinguish the current direction.
Is there any way pzem can distinguish the current direction?
Because I want to have kWh import and kWh export
please help!

**Comment by popeye2019** [comment] 2020-10-02 09:51
Hi, if you know how tell me, I'm interrested.

**Comment by luckywang95** [comment] 2020-10-04 01:05
https://forum.arduino.cc/index.php?topic=621693.15

Based on this post, it doesn't seem like it is measuring 2 ways. Quite sad.

**Comment by mandulaj** [comment] 2020-10-19 07:32
Unfortunately, there is no way to measure the phase between the voltage and current directly using the PZEM. The power factor is the cosine of the phase and thus doesn't contain information which way the power is flowing. This is why I decided to build my own power meter which will allow the direction to be determined.

**Comment by mandulaj** [comment] 2021-01-23 10:47
Duplicate of #2

**Closed by mandulaj** 2021-01-23 10:47 UTC

**Comment by ThomasDiebel** [comment] 2021-03-10 04:54
> Unfortunately, there is no way to measure the phase between the voltage and current directly using the PZEM. The power factor is the cosine of the phase and thus doesn't contain information which way the power is flowing. This is why I decided to build my own power meter which will allow the direction to be determined.

Thanks for the examples. Got any results on building?
