### ISSUE TITLE
pzem-004t v3 reset energy alone after => 60kw 

### ISSUE THREAD

**Issue by capblack** [mandulaj/PZEM-004T-v30#47] opened 2021-01-28 16:26 UTC
hello I built an energy meter of 3 faces with pzem-0004T v3 and I have the problem that the faces reset the accumulated energy after the 60kw approximately.
is a bug? thanks

https://youtu.be/ekmTViQi_cU

**Comment by mandulaj** [comment] 2021-01-29 11:42
Hey @capblack thats very odd, the specs range should be 0-9999.99kWh according to the datasheet, but truth be told, I could not test it as I don't have such an energy consumption. The video though is private so I can't see it. Would you mind setting it as unlisted instead?

**Comment by capblack** [comment] 2021-01-29 14:21
OK thanks for you reply and, in the video you can see the unit , but not the reset in question, that is my average consumption per two months about 1200kw , but @ the start a say is very precise, after 100kw the star to show 30% less and after feew weeks 70% less , and i say there is a problem , and I see the ridings come to 0 after aprox pass 60 kw
![Screenshot_2021-01-29-16-19-43-233_cc blynk](https://user-images.githubusercontent.com/16296480/106286160-03767c80-624e-11eb-92e7-b939b3524653.jpg)

**Comment by mandulaj** [comment] 2021-01-29 17:35
Hmm that is definitely a strange behavior... Sounds like some sort of a overflow. Could be in the PZEM or in the library code. I can't quite see anything obvious in the library code at the moment but I don't want to straight out blame it on the chip. I will have a closer look at this issue once I get around testing the library next week.

Unfortunately, I don't have power consumption quite high enough to test this thoroughly. I will try simulating it somehow but it would be really useful if you could send me the raw numbers that are coming from the PZEM chips. 

Currently there is no debug mode (will add that to the TODO list). Would you be so kind and modify the library slightly in order to print out the raw response during the value update?

If you could add this code:
```c++
Serial.println("Raw response:");
for(int i = 0; i < 25; i++){
    Serial.println(response[i], HEX);
}
Serial.println("End");
```

 after line 379 in the `PZEM004Tv30.cpp` library: https://github.com/mandulaj/PZEM-004T-v30/blob/e7f220220e5f765f5e1fd9963b9d69a053296c0e/PZEM004Tv30.cpp#L377-L379 and send me the serial output for your devices with Energy over 60kWh.

Note that this will print the raw response from the PZEMs to the standard `Serial` device. Change it to what ever serial interface you use for debugging (like for example `Serial2`).


## Temporary solution
In case you are reporting the energy to some sort of a database, you can set the code to reset the internal  energy counter of the PZEMs with the `.resetEnergy()` method once it gets over a certain margin (60kWh). In the database, you can keep track, how many times you had to reset and from that calculate the true aggregate energy. It's not a perfect solution but in case it really is the limitation of the chip, it will be the only option. 

I have had in mind for a while to perform a rigorous analysis of the true capabilities of the module and compare them to the manufacturer specifications. I would not be too surprised if the datasheet claims are slightly too optimistic.

**Comment by morganflint** [comment] 2021-02-28 10:04
Maybe the OP is having a similar problem that was addressed [here](https://community.blynk.cc/t/pzem-004t-v3-0-and-nodemcu-wemos-mini-running-on-blynk-how-to-procedure/39338/61).
Basically, it was due to using only 2 of the 4 bytes of the energy registers, so it resets when it reaches 65532 Wh (65.5kWh).
That was with another library (ModbusMaster), I haven't analyzed if this one has the same problem, but it's suspicious the OP has the problem around the same "magic number"

**Comment by capblack** [comment] 2021-02-28 10:59
Hello yes i change the busmaster with standart library and al is ok now no
reset energy ,and can see the acumulated in history thanks for

**Comment by brunosso** [comment] 2022-03-07 19:40
I don't understand if this issue is fixed or not.
Thanks

**Comment by pioioTwo** [comment] 2022-03-22 23:31
ia have problem, my code idem with examples

**Comment by pioioTwo** [comment] 2022-03-22 23:32
my pzem its reset energy after 65 Wh

**Comment by capblack** [comment] 2022-03-22 23:36
yes i fix the problem , was the totals storage variable had an unsing_intiger, when I changed it to a long fix the bug :)

**Comment by pioioTwo** [comment] 2022-03-23 22:58
can you give me an example

**Comment by mandulaj** [comment] 2022-03-24 11:21
Yes @capblack, could you push your changes as a pull request. I am quite curious what the issue is. I had a look over the code and I am using uint32_t which should be large enough to hold the energy values. 

If possible, I would like to avoid going to a long but perhaps its the unsigned nature that's causing the problem. Would have to investigate closer.

**Comment by capblack** [comment] 2022-03-24 11:29
Hi Jakub You coul download full code herehttps://drive.google.com/drive/folders/1W3jGJp451KJDXy7BvQeOkArqFwXoovCk?usp=sharing and you could check it on https://www.youtube.com/watch?v=ekmTViQi_cU be in touch Sent from Mail for Windows From: Jakub MandulaSent: Thursday, March 24, 2022 1:21 PMTo: mandulaj/PZEM-004T-v30Cc: capblack; MentionSubject: Re: [mandulaj/PZEM-004T-v30] pzem-004t v3 reset energy alone after => 60kw (#47) Yes @capblack, could you push your changes as a pull request. I am quite curious what the issue is. I had a look over the code and I am using uint32_t which should be large enough to hold the energy values.If possible, I would like to avoid going to a long but perhaps its the unsigned nature that's causing the problem. Would have to investigate closer.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by capblack** [comment] 2022-10-11 09:16
Hi Jakub You coul download full code herehttps://drive.google.com/drive/folders/1W3jGJp451KJDXy7BvQeOkArqFwXoovCk?usp=sharing and you could check it on https://www.youtube.com/watch?v=ekmTViQi_cU be in touch Sent from Mail for Windows From: Jakub MandulaSent: Thursday, March 24, 2022 1:21 PMTo: mandulaj/PZEM-004T-v30Cc: capblack; MentionSubject: Re: [mandulaj/PZEM-004T-v30] pzem-004t v3 reset energy alone after => 60kw (#47) Yes @capblack, could you push your changes as a pull request. I am quite curious what the issue is. I had a look over the code and I am using uint32_t which should be large enough to hold the energy values.If possible, I would like to avoid going to a long but perhaps its the unsigned nature that's causing the problem. Would have to investigate closer.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by 123salee** [comment] 2022-11-14 14:48
TTGO T-CALL ESP32 CODE??

**Comment by mandulaj** [comment] 2022-11-14 15:59
@123salee could you please be a bit more specific? Is this related to this issue? Do you want example code? Do you have a problem?

**Comment by 123salee** [comment] 2022-11-15 00:05
Good day, do you have an example code for pzem004t using ttgo tcall esp32?
I have tried your code for hardserial but i think it is not for ttgo.thanks

**Comment by capblack** [comment] 2022-11-15 06:28
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}

**Comment by mandulaj** [comment] 2023-02-02 13:05
Closing as resolved.

**Closed by mandulaj** 2023-02-02 13:05 UTC
Labels: bug, help wanted, hardware
