### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by pmoser56** [mandulaj/PZEM-004T-v30#9] opened 2019-08-05 17:29 UTC
Thanks a lot for your library. It works really well.
What does not work is the usage of "NAN" in the SoftwareSerial example. I replaced it with "isnan" and then it works really well so far. I created a 3-phase circuit with an esp8266 with 3 SoftwareSerial interfaces and mqtt readout. Thanks a lot for your work.

**Comment by mandulaj** [comment] 2019-10-01 22:13
It looks like SoftwareSerial is not as hardware independent as I thought. I am considering rewriting it anyways. Thanks!

**Comment by mandulaj** [comment] 2019-10-01 22:26
Yeah I had a second look and now I see the problem. I will change this, thanks for pointing it out.

**Comment by frthecrow** [comment] 2019-10-05 14:21
Hellow
Have you try it with Mysensors.
I have a probleme with this code.
Could you help me ?

[Watmetre_Mysensors_2019-10-04.zip](https://github.com/mandulaj/PZEM-004T-v30/files/3693347/Watmetre_Mysensors_2019-10-04.zip)

thanks

**Comment by mandulaj** [comment] 2019-10-05 15:14
> Hellow
> Have you try it with Mysensors.
> I have a probleme with this code.
> Could you help me ?
> 
> [Watmetre_Mysensors_2019-10-04.zip](https://github.com/mandulaj/PZEM-004T-v30/files/3693347/Watmetre_Mysensors_2019-10-04.zip)
> 
> thanks

Hi, could you please specify more details regarding your problem? Are you not getting the right values? No values at all? Errors? Does it not compile? I can't compile your code as there are some files missing... You can paste the results from your console and then I can help you but like this, there are way too many variables that could be the cause of your issue...
cheers!

**Comment by frthecrow** [comment] 2019-10-05 16:16
Hi 

Picture for speeking.


Thansk

Provenance : Courrier pour Windows 10

De : Jakub Mandula
Envoyé le :samedi 5 octobre 2019 17:14
À : mandulaj/PZEM-004T-v30
Cc : frthecrow; Comment
Objet :Re: [mandulaj/PZEM-004T-v30] Library (#9)

Hellow
Have you try it with Mysensors.
I have a probleme with this code.
Could you help me ?
Watmetre_Mysensors_2019-10-04.zip
thanks
Hi, could you please specify more details regarding your problem? Are you not getting the right values? No values at all? Errors? Does it not compile? I can't compile your code as there are some files missing... You can paste the results from your console and then I can help you but like this, there are way too many variables that could be the cause of your issue...
cheers!

**Comment by frthecrow** [comment] 2019-10-05 16:18
![Capture 2 PB Start with 5 MYMESSAGE](https://user-images.githubusercontent.com/56197145/66257674-7d9f0a00-e79c-11e9-9121-c5f59c56528b.PNG)
![Capture 3 PB compet MYMESSAGE](https://user-images.githubusercontent.com/56197145/66257675-7d9f0a00-e79c-11e9-820c-97d94a3da328.PNG)
![Capture 4 OK with 4](https://user-images.githubusercontent.com/56197145/66257676-7d9f0a00-e79c-11e9-995e-aba57ca70dd0.PNG)
![Capture 1 ok](https://user-images.githubusercontent.com/56197145/66257677-7e37a080-e79c-11e9-8d10-6969ae0b2a50.PNG)

**Comment by frthecrow** [comment] 2019-10-06 15:59
Hello
Ok With an other computer.

Excuse me
thanks

**Comment by ruimiguelsa** [comment] 2019-10-24 09:26
> 
> 
> Thanks a lot for your library. It works really well.
> What does not work is the usage of "NAN" in the SoftwareSerial example. I replaced it with "isnan" and then it works really well so far. I created a 3-phase circuit with an esp8266 with 3 SoftwareSerial interfaces and mqtt readout. Thanks a lot for your work.

Hello, 
Can you post your code? Thanks in advance.

**Comment by mandulaj** [comment] 2019-11-19 20:15
I think now this issue is resolved in #14

**Closed by mandulaj** 2019-11-19 20:15 UTC
Labels: bug
